// Copyright © 2026 Spirit-Schema. All rights reserved.
// Licensed under the Tarkov Server Guard Source-Available Freeware License 1.0. See LICENSE.

namespace TarkovServerReporter
{
    /// <summary>
    /// Text introduced by the v0.8.4 test build. Keeping this catalog in a separate
    /// partial keeps the operation-note and party-block vocabulary reviewable as a unit.
    /// </summary>
    public static partial class AppText
    {
        // Presentation-only translation of app-generated diagnostic messages.
        // Never call this for memo text, nicknames, tags, paths, or other user data.
        // The backend and persisted errors retain their original values.
        public static string TranslateDiagnostic(string message, string fallbackKey)
        {
            if (string.IsNullOrWhiteSpace(message)) return fallbackKey == null ? message : Get(fallbackKey);
            if (CurrentLanguage != EnglishLanguage) return message;
            foreach (System.Collections.Generic.KeyValuePair<string, string> item in Korean)
            {
                if (!item.Key.StartsWith("Diagnostic.", System.StringComparison.Ordinal)) continue;
                if (message == item.Value) return Get(item.Key);
                if (message.Length > 4096 || item.Value.IndexOf("{0}", System.StringComparison.Ordinal) < 0) continue;
                string pattern = "\\A" + System.Text.RegularExpressions.Regex.Escape(item.Value)
                    .Replace("\\{0}", "(?<a0>.*?)").Replace("\\{1}", "(?<a1>.*?)") + "\\z";
                try
                {
                    var match = System.Text.RegularExpressions.Regex.Match(message, pattern,
                        System.Text.RegularExpressions.RegexOptions.Singleline,
                        System.TimeSpan.FromMilliseconds(100));
                    if (match.Success) return Format(item.Key, match.Groups["a0"].Value, match.Groups["a1"].Value);
                }
                catch (System.Text.RegularExpressions.RegexMatchTimeoutException) { }
            }
            string exact = TranslateLiteral(message);
            if (exact != message) return exact;
            foreach (char ch in message)
                if ((ch >= '\u3131' && ch <= '\u318E') || (ch >= '\uAC00' && ch <= '\uD7A3'))
                    return fallbackKey == null ? message : Get(fallbackKey);
            return message;
        }

        private static void AddV084CatalogEntries()
        {
            // Compatibility aliases used by the new forms.
            Add("Common.All", "전체", "All");
            Add("Common.Delete", "삭제", "Delete");
            Add("Common.Game.Arena", "Arena", "Arena");
            Add("Common.Game.Eft", "EFT", "EFT");
            Add("Common.Open", "열기", "Open");
            Add("Common.Refresh", "새로 고침", "Refresh");
            Add("Common.Save", "저장", "Save");

            // Application settings and user-configurable overlay shortcuts.
            Add("Settings.WindowTitle", "설정", "Settings");
            Add("Settings.Button", "설정", "Settings");
            Add("Settings.Tooltip", "표시 언어를 설정합니다.", "Choose the display language.");
            Add("Settings.SaveFailed", "설정을 저장하지 못했습니다: {0}", "Couldn't save settings: {0}");
            Add("Settings.SaveFailedUnknown", "설정을 적용할 수 없습니다.", "Settings could not be applied.");

            // Unified memo workspace and editor.
            Add("Memo.Legacy.RaidNoteTitle", "레이드 메모", "Raid Note");
            Add("Memo.Legacy.UserReportTitle", "유저신고 메모", "Report Note");
            Add("Memo.Legacy.ReadOnlySourceNotice", "통합 메모로 가져온 원본 · 이 창의 변경은 동기화되지 않으므로 읽기 전용", "Imported original · Read-only. Changes here would not update the imported copy.");

            // Existing user-facing forms reached from the main window.
            Add("Usage.WindowTitle", "사용방법", "Usage Guide");
            Add("Usage.AccessibleName", "Tarkov Server Guard 사용방법", "Tarkov Server Guard Usage Guide");
            Add("Usage.MatchLine", "매칭 로딩 중 차단한 서버가 매칭되면", "If matchmaking assigns you a blocked server,");
            Add("Usage.ErrorLine", "화면이 잠시 멈춘 후 접속실패가 표시될 수 있습니다.", "loading may pause before a connection error appears.");
            Add("Usage.NormalLine", "이는 차단한 서버로의 접속을 막아주는 정상 작동입니다.", "This is expected: TSG has blocked that server connection.");
            Add("Usage.Step1.Prefix", "1. 접속실패가 표시되면 ", "1. Instead of ");
            Add("Usage.Step1.Avoid", "종료", "Exit");
            Add("Usage.Step1.Middle", " 대신 ", ", select ");
            Add("Usage.Step1.Action", "ESCAPE FROM TARKOV", "ESCAPE FROM TARKOV");
            Add("Usage.Step1.Suffix", " 선택", ".");
            Add("Usage.Step2.Prefix", "2. 다음 화면에서 ", "2. Instead of ");
            Add("Usage.Step2.Avoid", "재진입", "Reconnect");
            Add("Usage.Step2.Middle", " 대신 ", ", select ");
            Add("Usage.Step2.Action", "나가기 확인", "Confirm Leave");
            Add("Usage.Step2.Suffix", " 선택 (장비는 보존됩니다)", ". Your gear is kept.");
            Add("Usage.Step3", "3. 축하합니다! 차단한 서버로의 접속을 막았습니다.\r\n   다시 매칭해 주세요.", "3. Start matchmaking again.");
            Add("Usage.Confirm", "확인", "Got It");

            Add("Arena.Warning.Title", "아레나 서버 차단", "Block Arena Server");
            Add("Arena.Warning.Body", "아레나 서버 차단 시 탈주 페널티 적용 여부는 확인되지 않았습니다. 그래도 차단하시겠습니까?", "It is not confirmed whether blocking an Arena server can trigger a match-abandonment penalty. Block this server anyway?");

            Add("RaidNote.Section.Free", "자유메모", "Notes");
            Add("RaidNote.Placeholder", "예시) 귀중품 파밍 장소, 이동 동선, 저격 포인트, 보스 스폰 위치 등을 자유롭게 기록해 보세요.", "Write anything you'd like to remember about this raid.");
            Add("RaidNote.NicknamePlaceholder", "유저닉네임\r\n1.\r\n2.\r\n3.", "Player names\r\n1.\r\n2.\r\n3.");
            Add("RaidNote.Attachments.Section", "스크린샷 첨부 · 파일은 복사하거나 업로드하지 않고 경로만 저장합니다", "Screenshots · Links to local files");
            Add("RaidNote.Attach", "첨부", "Attach");
            Add("RaidNote.OpenFolder", "폴더 열기", "Open Folder");
            Add("RaidNote.Detach", "첨부 해제", "Remove Link");
            Add("RaidNote.Tags", "태그 (,)쉼표로 구분", "Tags · Separate with commas");
            Add("RaidNote.LocalOnly", "이 메모는 게임 로그와 별도로 로컬에 보관됩니다.", "This note is stored locally, separately from the game logs.");
            Add("RaidNote.OpenStorage", "메모 저장 폴더 열기", "Open Notes Folder");
            Add("RaidNote.TimeUnknown", "시각 확인 안 됨", "Time Unavailable");
            Add("RaidNote.AttachDialog.Title", "스크린샷 첨부", "Attach Screenshots");
            Add("RaidNote.AttachDialog.Filter", "이미지 파일|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.webp", "Image files|*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.webp");
            Add("RaidNote.AttachedCount", "{0}개 파일을 첨부했습니다.", "Files attached: {0}.");
            Add("RaidNote.AttachmentRejected", "지원하는 로컬 이미지 파일만 첨부할 수 있습니다. 제외 {0}개", "Only supported local images can be attached. Files skipped: {0}.");
            Add("RaidNote.AttachmentUnsafe", "지원하는 로컬 이미지·동영상 파일만 열 수 있습니다.", "Only supported local image and video files can be opened.");
            Add("RaidNote.AttachmentMissing", "첨부한 파일을 찾을 수 없습니다. 경로가 이동되었는지 확인해 주세요.", "The attached file could not be found. Check whether it was moved.");
            Add("RaidNote.AttachmentFolderUnsafe", "지원하는 로컬 이미지·동영상 파일의 위치만 열 수 있습니다.", "Only folders containing supported local image and video files can be opened.");
            Add("RaidNote.AttachmentFolderMissing", "첨부 경로의 폴더를 찾을 수 없습니다.", "The attachment folder could not be found.");
            Add("RaidNote.Saved", "메모를 저장했습니다.", "Note saved.");
            Add("RaidNote.SaveFailed", "메모를 저장하지 못했습니다.\r\n{0}", "Couldn't save the note.\r\n{0}");
            Add("RaidNote.NoSavedNote", "삭제할 저장 메모가 없습니다.", "There is no saved note to delete.");
            Add("RaidNote.DeletePrompt", "이 레이드의 메모를 삭제할까요? 첨부한 원본 스크린샷은 삭제하지 않습니다.", "Delete this raid note? The original attached files will not be deleted.");
            Add("RaidNote.DeleteTitle", "레이드 메모 삭제", "Delete Raid Note");
            Add("RaidNote.DeleteFailed", "메모를 삭제하지 못했습니다.\r\n{0}", "Couldn't delete the note.\r\n{0}");
            Add("RaidNote.OpenFolderFailed", "메모 폴더를 열지 못했습니다: {0}", "Couldn't open the notes folder: {0}");
            Add("RaidNote.UnsavedPrompt", "저장하지 않은 변경 사항이 있습니다. 저장하고 닫을까요?", "Save your changes before closing?");
            Add("RaidNote.Timestamp", "생성 {0}   ·   수정 {1}", "Created {0}   ·   Updated {1}");
            Add("RaidNote.Unsaved", "저장하지 않은 변경 사항이 있습니다.", "Unsaved changes");
            Add("RaidNote.OpenFailed", "열지 못했습니다: {0}", "Couldn't open it: {0}");
            Add("RaidNote.MissingRecordKey", "저장된 메모 키가 없습니다.", "The saved raid note has no key.");

            Add("UserReport.Privacy", "유저네임·신고사유·게임·맵·레이드 시각·신고 건수만 로컬 저장합니다.\r\n게임 로그 원문·계정 ID·SID·경로는 저장·전송하지 않습니다.", "These notes stay on this PC; they do not submit reports to Battlestate Games.\r\nOnly names, reasons, game, map, raid time, and report count are saved—never raw logs, account IDs, SIDs, or paths.");
            Add("UserReport.OpenFolder", "보관 폴더 열기", "Open Notes Folder");
            Add("UserReport.SummaryLimited", "성공 확인된 신고 {0}건 · 화면 과부하를 막기 위해 앞의 {1}건을 표시합니다.", "Reports logged: {0} · Showing the first {1} for better performance.");
            Add("UserReport.Summary", "성공 확인된 신고 {0}건 · 일반 레이드 메모와 함께 메모보관함에 저장됩니다.", "Reports logged: {0} · Saved alongside your raid notes.");
            Add("UserReport.Section", "신고 정보", "Report Details");
            Add("UserReport.PlayerLabel", "{0}. 유저네임:", "{0}. Player:");
            Add("UserReport.ReasonLabel", "신고사유:", "Reason:");
            Add("UserReport.Legacy", "기존 메모 (v0.6.6) · 원문을 그대로 보존합니다.", "Legacy Note (v0.6.6) · Original text");
            Add("UserReport.Saved", "유저신고 메모를 저장했습니다.", "Report note saved.");
            Add("UserReport.SaveFailed", "저장하지 못했습니다: {0}", "Couldn't save: {0}");
            Add("UserReport.NoSaved", "저장된 유저신고 메모가 없습니다.", "There is no saved report note.");
            Add("UserReport.DeletePrompt", "이 유저신고 메모를 삭제할까요? 일반 레이드 메모에는 영향을 주지 않습니다.", "Delete this report note? The raid note will not be affected.");
            Add("UserReport.DeleteTitle", "유저신고 메모 삭제", "Delete Report Note");
            Add("UserReport.Deleted", "유저신고 메모를 삭제했습니다.", "Report note deleted.");
            Add("UserReport.DeleteFailed", "삭제하지 못했습니다: {0}", "Couldn't delete: {0}");
            Add("UserReport.OpenFolderFailed", "보관 폴더를 열지 못했습니다: {0}", "Couldn't open the storage folder: {0}");
            Add("UserReport.TimestampUnsaved", "생성: 저장 전 · 수정: 저장 전", "Not saved yet");
            Add("UserReport.Timestamp", "생성: {0:yyyy-MM-dd HH:mm:ss} · 수정: {1:yyyy-MM-dd HH:mm:ss}", "Created: {0:yyyy-MM-dd HH:mm:ss} · Updated: {1:yyyy-MM-dd HH:mm:ss}");
            Add("UserReport.UnsavedPrompt", "변경한 유저신고 메모를 저장할까요?", "Save changes to this report note?");
            Add("UserReport.SaveConfirmTitle", "저장 확인", "Save Changes");
            Add("UserReport.TemplateLine", "{0}. 유저네임:                         신고사유:", "{0}. Player:                    Reason:");
            Add("UserReport.MissingRecordKey", "저장된 유저신고 메모 키가 없습니다.", "The saved report note has no key.");

            // Blocked-server window. IPs, user notes, file paths, and raw external
            // diagnostics are supplied as format arguments and are never translated.
            Add("BlockedServers.Notice.ProcessExit", "창을 닫으면 TSG는 완전히 종료됩니다. 백그라운드에 상주하지 않아 TSG 프로세스가 CPU·메모리·네트워크를 추가로 사용하지 않습니다.", "TSG stops running when you close the app.");
            Add("BlockedServers.Notice.RulesPersist", "차단 리스트는 Windows 방화벽에 저장되므로 해당 앱 종료·PC 재부팅 후에도 유지되며, 앱에서 해제할 때까지 계속 적용됩니다.", "Windows Firewall keeps your blocks active after TSG closes or your PC restarts, until you unblock them.");
            Add("BlockedServers.Notice.PartyLocal", "차단 리스트는 이 PC에만 적용됩니다. 파티 매칭에서는 각 파티원이 같은 서버를 차단해야 모든 파티원의 접속을 막을 수 있습니다.", "Blocks apply to this PC only. Each party member must block the same IPs to keep the whole party off those servers.");
            Add("BlockedServers.Notice.PersistenceA11y", "앱 종료와 차단 리스트 유지 안내", "TSG exit and block-list persistence notice");
            Add("BlockedServers.Notice.PartyA11y", "파티 매칭의 로컬 차단 적용 범위 안내", "Local block scope for party matchmaking");
            Add("BlockedServers.Ping.BlockedText", "차단 중 · 측정 불가", "Unavailable");
            Add("BlockedServers.Ping.BlockedHelp", "차단 규칙이 해당 IP의 모든 아웃바운드 통신(ICMP 포함)을 막으므로 차단 중에는 현재 핑을 측정할 수 없습니다. 해제 후 메인 화면에서 조회해 주세요.", "This block also prevents ping traffic (ICMP). To check the current ping, unblock the server and scan it from the main window.");
            Add("BlockedServers.Refresh.Help", "Windows 방화벽의 차단 규칙 목록을 다시 확인합니다.", "Refreshes the managed block rules from Windows Firewall.");
            Add("BlockedServers.Sort.Help", "클릭할 때마다 오름차순, 내림차순, 기본 순서로 정렬합니다.", "Click to cycle through ascending, descending, and default order.");
            Add("BlockedServers.Selection.SelectAll", "전체 선택", "Select All");
            Add("BlockedServers.Selection.ClearAll", "전체 해제", "Clear All");
            Add("BlockedServers.Selection.SelectAllVerb", "전체 선택", "select all");
            Add("BlockedServers.Selection.ClearAllVerb", "전체 해제", "clear all");
            Add("BlockedServers.Selection.HeaderDescription", "차단 해제 대상을 고르는 체크박스 열입니다. 헤더를 누르면 {0}합니다. 현재 {1}개 중 {2}개가 선택되어 있습니다.", "Checkbox column for choosing servers to unblock. Activate the header to {0}. {2} of {1} selected.");
            Add("BlockedServers.Selection.HeaderName", "차단 서버 선택 열 헤더", "Blocked-server selection column header");
            Add("BlockedServers.Selection.HeaderTooltip", "차단 해제 대상을 전체 선택하거나 전체 해제합니다.", "Select or clear all unblock targets.");
            Add("BlockedServers.Selection.Count", "선택 {0}개", "{0} selected");
            Add("BlockedServers.Selection.CountA11y", "선택된 차단 서버 수: {0}개", "Selected blocked servers: {0}");
            Add("BlockedServers.Selection.Description", "현재 차단 서버 {0}개 중 {1}개가 선택되어 있습니다.", "{1} of {0} blocked servers selected.");
            Add("BlockedServers.Selection.GridDescription", "선택 체크박스 열에서 차단 해제할 서버를 고릅니다. 현재 차단 서버 {0}개 중 {1}개가 선택되어 있습니다. 선택 열 헤더는 전체 선택 또는 전체 해제하고 Ctrl+A는 전체 선택합니다. 현재 핑은 차단 규칙이 ICMP를 포함한 통신을 막아 차단 중에는 측정할 수 없습니다.", "Choose servers to unblock in the checkbox column. {1} of {0} blocked servers selected. Use the column header to select or clear all; Ctrl+A selects all. Current ping is unavailable while a firewall rule blocks traffic, including ICMP.");
            Add("BlockedServers.Grid.Name", "차단 서버 목록", "Blocked Servers List");
            Add("BlockedServers.Button.UnblockAll", "전체 해제", "Unblock All");
            Add("BlockedServers.Button.UnblockSelected", "선택 해제", "Unblock Selected");
            Add("BlockedServers.Button.UnblockOne", "해제", "Unblock");
            Add("BlockedServers.Button.UnblockColumn", "개별해제", "Unblock");
            Add("BlockedServers.Button.UnblockSelectedA11y", "선택한 서버의 Windows 방화벽 차단만 해제합니다.", "Unblocks only the selected servers in Windows Firewall.");
            Add("BlockedServers.Button.UnblockAllA11y", "목록에 있는 모든 서버의 Windows 방화벽 차단을 해제합니다.", "Unblocks every server shown in this Windows Firewall list.");
            Add("BlockedServers.Button.RefreshA11y", "차단 규칙 목록 새로고침", "Refresh Block Rules");
            Add("BlockedServers.Busy.CloseBlocked", "방화벽·파일 작업과 최종 확인이 끝난 뒤 창을 닫을 수 있습니다.", "Please wait for the operation to finish before closing this window.");
            Add("BlockedServers.Column.Status", "상태", "Status");
            Add("BlockedServers.Column.CurrentPingA11y", "현재 핑 열", "Current Ping Column");
            Add("BlockedServers.Column.Location", "데이터센터 / 지역", "Location");
            Add("BlockedServers.Column.Unblock", "개별해제", "Unblock");
            Add("BlockedServers.Unknown", "확인 안 됨", "Not Verified");
            Add("BlockedServers.Loading", "앱이 관리하는 차단 규칙을 확인하는 중…", "Loading TSG block rules…");
            Add("BlockedServers.LoadFailed", "서버차단현황을 확인하지 못했습니다.", "Couldn't load blocked servers.");
            Add("BlockedServers.FirewallUnavailable", "Windows 방화벽을 확인할 수 없습니다.", "Windows Firewall is unavailable.");
            Add("BlockedServers.Empty", "현재 앱이 관리하는 차단 서버가 없습니다.", "No servers blocked by TSG.");
            Add("BlockedServers.Count", "현재 {0}개 서버가 차단되어 있습니다.", "Blocked servers: {0}");
            Add("BlockedServers.RefreshEmpty", "현재 규칙과 v1.1.1 호환 규칙을 모두 확인했습니다.", "Checked TSG rules, including compatible v1.1.1 rules.");
            Add("BlockedServers.RefreshReady", "해제할 서버를 선택하거나 행의 ‘해제’를 누르세요.", "Select servers to unblock, or click Unblock in a row.");
            Add("BlockedServers.RowStatus.Blocked", "차단 중", "Blocked");
            Add("BlockedServers.Rule.Current", "현재 규칙", "Current Rule");
            Add("BlockedServers.Rule.Legacy", "v1.1.1 규칙", "v1.1.1 Rule");
            Add("BlockedServers.Rule.CurrentAndLegacy", "현재 + v1.1.1", "Current + v1.1.1");
            Add("BlockedServers.UnblockOnePrompt", "{0} 서버의 차단을 해제할까요?", "Unblock server {0}?");
            Add("BlockedServers.UnblockConfirmTitle", "차단 해제 확인", "Confirm Unblock");
            Add("BlockedServers.Note.Title", "차단 메모", "Block Note");
            Add("BlockedServers.Note.LocalOnly", "{0} · 이 PC에만 저장됩니다.", "{0} · Stored only on this PC");
            Add("BlockedServers.Note.Example", "높은 핑, 패킷손실, 반복 끊김 등", "e.g. high ping, packet loss, or repeated disconnects");
            Add("BlockedServers.Note.InputHelp", "선택 입력 · 한 줄, 최대 300자", "Optional · Up to 300 characters on one line");
            Add("BlockedServers.Note.SaveFailed", "차단 메모를 저장하지 못했습니다.", "Couldn't save the block note.");
            Add("BlockedServers.Note.DeleteFailed", "차단 메모를 삭제하지 못했습니다.", "Couldn't delete the block note.");
            Add("BlockedServers.Note.Saved", "{0} 서버의 차단 메모를 저장했습니다.", "Saved the block note for {0}.");
            Add("BlockedServers.Note.Deleted", "{0} 서버의 차단 메모를 삭제했습니다.", "Deleted the block note for {0}.");
            Add("BlockedServers.Note.SavedCell", "저장된 차단 메모", "View Note");
            Add("BlockedServers.Note.AddCell", "차단 메모 추가", "Add Note");
            Add("BlockedServers.Note.AddTooltip", "차단 메모를 추가합니다.", "Add a block note.");
            Add("BlockedServers.Backup.ExportTitle", "차단 목록 내보내기", "Export Block List");
            Add("BlockedServers.Backup.ImportTitle", "차단 목록 불러오기", "Import Block List");
            Add("BlockedServers.Backup.Filter", "Tarkov Server Guard 차단 목록 (*.json)|*.json|모든 파일 (*.*)|*.*", "Tarkov Server Guard Block List (*.json)|*.json|All files (*.*)|*.*");
            Add("BlockedServers.Backup.CheckingRules", "Windows 방화벽의 실제 관리 규칙을 확인하는 중…", "Checking TSG rules in Windows Firewall…");
            Add("BlockedServers.Backup.QueryFailed", "현재 차단 규칙을 확인하지 못했습니다.", "Couldn't verify the current block rules.");
            Add("BlockedServers.Backup.CreateFailed", "차단 목록 백업을 만들지 못했습니다.", "Couldn't create the block-list backup.");
            Add("BlockedServers.Backup.Empty", "현재 백업할 복원 가능한 앱 관리 차단 규칙이 없어 파일을 저장하지 않았습니다.", "No eligible TSG blocks to back up. No file was saved.");
            Add("BlockedServers.Backup.SaveFailed", "백업 파일 저장 실패: {0}", "Couldn't save the backup file: {0}");
            Add("BlockedServers.Backup.ExportSuccess", "차단 서버 {0}개를 {1} 파일로 저장했습니다.", "Saved {0} blocked servers to {1}.");
            Add("BlockedServers.Backup.ExportExcluded", " 공인 IPv4가 아닌 관리 규칙 {0}개는 제외했습니다.", " Rules skipped (not public IPv4 addresses): {0}.");
            Add("BlockedServers.Backup.Validating", "백업 파일의 형식·크기·주소를 검증하는 중…", "Validating the backup file's format, size, and addresses…");
            Add("BlockedServers.Backup.ReadFailed", "백업 파일을 읽지 못했습니다: {0}", "Couldn't read the backup file: {0}");
            Add("BlockedServers.Backup.Unsupported", "지원하지 않는 차단 목록 백업입니다.", "This block-list backup is not supported.");
            Add("BlockedServers.Backup.Preview", "새로 차단 {0}개 · 이미 차단됨 {1}개 · 적용 제외 {2}개를 확인했습니다.", "New: {0} · Already blocked: {1} · Excluded: {2}");
            Add("BlockedServers.Backup.VerifyingExisting", "이미 차단된 서버의 백업 정보를 최종 확인하는 중…", "Restoring missing details for servers already blocked…");
            Add("BlockedServers.Backup.Applying", "선택한 {0}개 서버를 한 번의 관리자 권한 요청으로 차단하는 중…", "Blocking {0} selected servers… Approve the Windows administrator prompt to continue.");
            Add("BlockedServers.Backup.RestoreSummary", "새 차단 {0}개 · 최종 확인 {1}개 · 실패 {2}개", "New blocks: {0} · Confirmed: {1} · Failed: {2}");
            Add("BlockedServers.Backup.MetadataFailedSuffix", " · 백업 정보 저장 실패", " · Failed to save backup details");
            Add("BlockedServers.Backup.RestoreResultTitle", "차단 목록 복원 결과", "Block List Restore Results");
            Add("BlockedServers.Backup.FinalRuleMissing", "최종 앱 관리 차단 규칙이 확인되지 않았습니다.", "Couldn't confirm that the TSG block rule exists.");
            Add("BlockedServers.Backup.MetadataRestoreFailed", "방화벽 차단은 최종 확인했지만 비어 있던 지역·메모·차단시각 일부를 저장하지 못했습니다.", "The servers are blocked, but some region, note, or block-time details couldn't be restored.");
            Add("BlockedServers.Unblock.NoneSelected", "해제할 서버를 먼저 선택해 주세요.", "Select at least one server to unblock.");
            Add("BlockedServers.Unblock.SelectedTitle", "선택 차단 해제", "Unblock Selected Servers");
            Add("BlockedServers.Unblock.SelectedPrompt", "선택한 {0}개 서버의 차단을 해제할까요?", "Unblock the {0} selected servers?");
            Add("BlockedServers.Unblock.AllPrompt", "앱이 관리하는 차단 서버 {0}개를 모두 해제할까요?\r\n\r\nTarkov Server Guard의 현재 규칙과 v1.1.1 호환 규칙만 삭제합니다.\r\n사용자가 직접 만든 다른 방화벽 규칙은 삭제하지 않습니다.", "Unblock all {0} app-managed servers?\r\n\r\nOnly current Tarkov Server Guard rules and v1.1.1-compatible rules will be removed.\r\nOther firewall rules you created will not be changed.");
            Add("BlockedServers.Unblock.AllTitle", "전체 차단 해제 확인", "Confirm Unblock All");
            Add("BlockedServers.Unblock.Working", "선택한 {0}개 서버의 차단을 해제하는 중…", "Unblocking {0} selected servers…");
            Add("BlockedServers.Unblock.Succeeded", "{0}개 서버의 차단을 해제했습니다.", "Servers unblocked: {0}.");
            Add("BlockedServers.Unblock.SucceededCleanupFailed", "{0}개 서버를 해제했지만 로컬 표시 정보 정리에 실패했습니다.", "Servers unblocked: {0}. Their saved display details couldn't be removed.");
            Add("BlockedServers.Unblock.More", " 외 {0}개", " and {0} more");
            Add("BlockedServers.Unblock.Partial", "{0}개 해제, {1}개 실패: {2}", "Unblocked {0}; {1} failed: {2}");
            Add("BlockedServers.Unblock.Failed", "차단 해제를 완료하지 못했습니다.", "Couldn't complete the unblock operation.");

            // Legacy raid-note and player-report archive.
            Add("NoteArchive.Title", "메모 보관함", "Saved Notes");
            Add("NoteArchive.Search.Label", "검색", "Search");
            Add("NoteArchive.Search.Help", "본문·태그·맵·게임·유저명·신고사유를 검색합니다. 여러 단어는 모두 포함해야 합니다. Ctrl+F: 검색, Esc: 검색어 지우기", "Search notes, tags, maps, games, player names, and report reasons. Every search word must match. Ctrl+F: search; Esc: clear search text.");
            Add("NoteArchive.Filter.Label", "종류", "Type");
            Add("NoteArchive.Filter.All", "전체 메모", "All Notes");
            Add("NoteArchive.Filter.Raid", "레이드 메모", "Raid Note");
            Add("NoteArchive.Filter.Report", "유저신고 메모", "Report Note");
            Add("NoteArchive.Search.Clear", "초기화", "Clear");
            Add("NoteArchive.Search.Count", "{0}개 표시 · 전체 {1}개", "Showing {0} of {1} notes");
            Add("NoteArchive.Search.Empty", "저장된 메모가 없습니다.\r\n메인 화면의 레이드 기록에서 메모나 유저신고 메모를 작성할 수 있습니다.", "No saved notes yet.\r\nSelect a connection in the main window to add a note.");
            Add("NoteArchive.Search.NoResults", "일치하는 메모가 없습니다.\r\n검색어를 바꾸거나 종류를 전체로 선택해 보세요.", "No matching notes.\r\nTry another search or select All Notes.");
            Add("NoteArchive.Backup.AllScope", "내보내기: 검색 결과와 관계없이 전체 메모", "Export includes all saved notes");
            Add("NoteArchive.Description", "게임 로그가 삭제된 뒤에도 일반 레이드 메모와 유저신고 메모를 확인할 수 있습니다.", "Your raid and report notes stay here even after the game logs are deleted.");
            Add("NoteArchive.Backup.ScreenshotNotice", "첨부 원본 파일은 백업에 포함되지 않으며, 로컬 파일 연결 경로만 함께 저장됩니다. 경로에는 사용자명 등 개인정보가 포함될 수 있으므로 공유 전에 확인해 주세요. 다른 PC에서 같은 경로에 파일이 없으면 첨부 파일을 열 수 없습니다.", "Backups contain attachment paths, not the files themselves. Paths may include your Windows user name. Review them before sharing. To open attachments on another PC, the files must be at the same paths.");
            Add("NoteArchive.Backup.ImportA11y", "메모 백업 불러오기", "Import Notes Backup");
            Add("NoteArchive.Backup.ImportDescription", "레이드 메모와 유저신고 메모 백업을 검증하고, 없는 메모만 복원합니다. 원본 파일 없이 검증된 로컬 첨부 경로만 복원합니다.", "Check a notes backup and restore missing notes and valid local attachment links. Existing notes and original files are left unchanged.");
            Add("NoteArchive.Backup.ExportA11y", "메모 통합 백업 내보내기", "Export Notes Backup");
            Add("NoteArchive.Backup.ExportDescription", "레이드 메모와 유저신고 메모를 하나의 JSON 파일로 저장합니다. {0}", "Saves raid and report notes in one JSON file. {0}");
            Add("NoteArchive.Grid.Name", "메모 선택 목록", "Saved Notes List");
            Add("NoteArchive.Grid.Description", "메모 선택 목록입니다. {0} 선택 열 머리글은 전체 선택 또는 전체 해제이며, Ctrl+A는 전체 선택입니다.", "Note selection list. {0} Use the selection-column header to select or clear all; Ctrl+A selects all.");
            Add("NoteArchive.Grid.SelectionSummary", "전체 메모 {0}개 중 {1}개가 선택되었습니다.", "{1} of {0} notes selected.");
            Add("NoteArchive.Grid.SelectHeaderTooltip", "모든 메모를 선택하거나 전체 해제합니다.", "Select or clear all notes.");
            Add("NoteArchive.Column.Kind", "종류", "Type");
            Add("NoteArchive.Column.RaidTime", "레이드 시각", "Raid Time");
            Add("NoteArchive.Column.Game", "게임", "Game");
            Add("NoteArchive.Column.MapGameType", "맵 · 게임유형", "Map · Game Type");
            Add("NoteArchive.Column.Preview", "메모 미리보기", "Note Preview");
            Add("NoteArchive.Column.TagsReports", "태그/신고", "Tags / Reports");
            Add("NoteArchive.Column.Updated", "최근 수정", "Last Updated");
            Add("NoteArchive.Sort.Help", "클릭할 때마다 오름차순, 내림차순, 기본 순서로 정렬합니다.", "Click to cycle through ascending, descending, and default order.");
            Add("NoteArchive.Loading", "메모를 불러오는 중…", "Loading notes…");
            Add("NoteArchive.Refreshing", "메모 목록을 새로고치는 중…", "Refreshing notes…");
            Add("NoteArchive.Button.DeleteCurrentA11y", "현재 메모 삭제", "Delete Current Note");
            Add("NoteArchive.Button.DeleteCurrentDescription", "현재 행에 포커스된 메모 1개를 삭제합니다.", "Deletes the note in the focused row.");
            Add("NoteArchive.Button.DeleteSelected", "선택 삭제", "Delete Selected");
            Add("NoteArchive.Button.DeleteSelectedNone", "체크박스로 선택한 메모가 없습니다.", "Check one or more notes to delete.");
            Add("NoteArchive.Button.DeleteSelectedCount", "체크박스로 선택한 메모 {0}개를 삭제합니다.", "Deletes the {0} notes selected with checkboxes.");
            Add("NoteArchive.Button.OpenFolder", "저장 폴더 열기", "Open Notes Folder");
            Add("NoteArchive.Button.Refresh", "새로고침", "Refresh");
            Add("NoteArchive.Kind.Raid", "레이드 메모", "Raid Note");
            Add("NoteArchive.Kind.PlayerReport", "유저신고 메모", "Report Note");
            Add("NoteArchive.ReportCount", "신고 {0}건", "Reports: {0}");
            Add("NoteArchive.ReportCountTooltip", "유저신고 {0}건", "In-game reports logged: {0}");
            Add("NoteArchive.Empty", "저장된 메모가 없습니다.", "There are no saved notes.");
            Add("NoteArchive.Count", "저장된 메모 {0}개 · 레이드 {1}개 · 유저신고 {2}개", "Saved: {0} · Raid notes: {1} · Report notes: {2}");
            Add("NoteArchive.LoadFailed", "메모 목록을 불러오지 못했습니다: {0}", "Couldn't load the note list: {0}");
            Add("NoteArchive.Delete.PlayerPrompt", "선택한 유저신고 메모를 삭제할까요? 일반 레이드 메모에는 영향을 주지 않습니다.", "Delete the selected report note? Its raid note will not be affected.");
            Add("NoteArchive.Delete.RaidPrompt", "선택한 레이드 메모를 삭제할까요? 첨부한 원본 스크린샷은 삭제하지 않습니다.", "Delete the selected raid note? Its original screenshot files will not be deleted.");
            Add("NoteArchive.Delete.Title", "메모 삭제", "Delete Note");
            Add("NoteArchive.Delete.Failed", "메모를 삭제하지 못했습니다: {0}", "Couldn't delete the note: {0}");
            Add("NoteArchive.Delete.BatchPrompt", "선택한 메모 {0}개를 삭제할까요?\r\n레이드 메모 {1}개 · 유저신고 메모 {2}개\r\n\r\n삭제한 메모는 복구할 수 없습니다. 레이드 메모에 첨부한 원본 스크린샷은 삭제하지 않습니다.", "Delete the {0} selected notes?\r\nRaid notes {1} · Report notes {2}\r\n\r\nDeleted notes cannot be recovered. Original screenshots attached to raid notes will not be deleted.");
            Add("NoteArchive.Delete.BatchTitle", "선택 메모 삭제", "Delete Selected Notes");
            Add("NoteArchive.Delete.Revalidating", "선택한 메모를 다시 확인하고 삭제하는 중…", "Rechecking and deleting the selected notes…");
            Add("NoteArchive.Delete.RefreshFailedSuffix", " · 목록 새로고침 실패", " · List refresh failed");
            Add("NoteArchive.Delete.BatchFailed", "선택한 메모를 삭제하지 못했습니다: {0}", "Couldn't delete the selected notes: {0}");
            Add("NoteArchive.Delete.StoreUnavailable", "현재 저장 목록을 확인하지 못했습니다.", "The current saved-note list could not be verified.");
            Add("NoteArchive.Delete.StillExists", "삭제 후에도 저장 항목이 남아 있습니다.", "The saved entry still exists after deletion.");
            Add("NoteArchive.Delete.ResultUnknown", "선택한 메모 삭제 결과를 확인하지 못했습니다.", "The selected-note deletion result could not be verified.");
            Add("NoteArchive.Delete.SucceededCount", "{0}개 삭제", "{0} deleted");
            Add("NoteArchive.Delete.MissingCount", "{0}개 이미 없음", "{0} already missing");
            Add("NoteArchive.Delete.FailedCount", "{0}개 실패", "{0} failed");
            Add("NoteArchive.Delete.NothingCurrent", "삭제할 현재 항목 없음", "No current items to delete");
            Add("NoteArchive.OpenFolderFailed", "저장 폴더를 열지 못했습니다: {0}", "Couldn't open the storage folder: {0}");
            Add("NoteArchive.Backup.Checking", "레이드 메모와 유저신고 메모를 확인하는 중…", "Checking raid and report notes…");
            Add("NoteArchive.Backup.CreateFailed", "메모 백업 데이터를 안전하게 만들지 못했습니다.", "Couldn't create the notes backup.");
            Add("NoteArchive.Backup.ExportPrompt", "일반 레이드 메모 {0}개와 유저신고 메모 {1}개를 하나의 JSON 파일로 저장합니다.\r\n\r\n{2}", "Save {0} raid notes and {1} report notes in one JSON file.\r\n\r\n{2}");
            Add("NoteArchive.Backup.ExportTitle", "메모 통합 백업 내보내기", "Export Notes Backup");
            Add("NoteArchive.Backup.Cancelled", "메모 백업 저장을 취소했습니다.", "Notes backup canceled.");
            Add("NoteArchive.Backup.SaveTitle", "메모 통합 백업 저장", "Save Notes Backup");
            Add("NoteArchive.Backup.SaveFilter", "TSG 메모 백업 (*.json)|*.json", "TSG Notes Backup (*.json)|*.json");
            Add("NoteArchive.Backup.ImportFilter", "TSG 메모 백업 (*.json)|*.json|모든 파일 (*.*)|*.*", "TSG Notes Backup (*.json)|*.json|All files (*.*)|*.*");
            Add("NoteArchive.Backup.Saving", "메모 백업 파일을 안전하게 저장하는 중…", "Saving notes backup…");
            Add("NoteArchive.Backup.Saved", "레이드 메모 {0}개 · 유저신고 메모 {1}개를 {2} 파일로 저장했습니다.", "Saved {0} raid notes and {1} report notes to {2}.");
            Add("NoteArchive.Backup.SaveFailed", "메모 백업 파일을 안전하게 저장하지 못했습니다.", "Couldn't save the notes backup file.");
            Add("NoteArchive.Backup.ImportTitle", "메모 통합 백업 불러오기", "Import Notes Backup");
            Add("NoteArchive.Backup.Validating", "메모 백업 파일을 검증하는 중…", "Validating the notes backup…");
            Add("NoteArchive.Backup.ValidationFailed", "메모 백업 파일을 안전하게 검증하지 못했습니다.", "Couldn't validate the notes backup.");
            Add("NoteArchive.Backup.RestoreCancelled", "메모 복원을 취소했습니다.", "Notes restore canceled.");
            Add("NoteArchive.Backup.RestoreSummary", "추가 {0}개 · 기존 항목 건너뜀 {1}개 · 실패 {2}개", "Added: {0} · Already saved: {1} · Failed: {2}");
            Add("NoteArchive.More", " 외 {0}개", " and {0} more");
            Add("NoteArchive.A11y.HeaderName", "메모 전체 선택 또는 전체 해제", "Select or Clear All Notes");
            Add("NoteArchive.A11y.HeaderDescription", "선택 열 머리글입니다. 클릭하면 모든 메모를 선택하거나 선택 해제합니다. {0}", "Selection-column header. Activate it to select or clear all notes. {0}");
            Add("NoteArchive.A11y.Checkbox", "메모 선택 체크박스", "Note Selection Checkbox");
            Add("NoteArchive.A11y.CheckboxRow", "메모 선택 체크박스 행 {0}", "Note Selection Checkbox, Row {0}");
            Add("NoteArchive.A11y.CheckboxDescription", "이 메모를 선택 삭제 대상에 포함합니다. 현재 {0} {1}", "Includes this note in the selected deletion. It is currently {0} {1}");
            Add("NoteArchive.A11y.Selected", "선택되었습니다.", "selected.");
            Add("NoteArchive.A11y.NotSelected", "선택되지 않았습니다.", "not selected.");
            Add("NoteArchive.UnknownError", "알 수 없는 오류", "Unknown error");

            Add("NoteRestore.Title", "메모 백업 복원 미리보기", "Notes Restore Preview");
            Add("NoteRestore.ResultSummary", "추가 {0}개 · 기존 항목 건너뜀 {1}개 · 실패 {2}개", "Added: {0} · Already saved: {1} · Failed: {2}");
            Add("NoteRestore.Policy", "기존 메모는 덮어쓰지 않으며, 체크한 새 메모만 추가합니다.\r\n원본 파일 없이 검증된 로컬 첨부 경로만 복원됩니다.", "Only checked new notes will be added. Existing notes are kept.\r\nAttachment links are restored; the files themselves are not copied.");
            Add("NoteRestore.ResultA11y", "메모 복원 결과", "Notes Restore Result");
            Add("NoteRestore.Button.Apply", "선택 항목 복원", "Restore Selected");
            Add("NoteRestore.Grid.Name", "복원할 메모 선택 목록", "Notes to Restore");
            Add("NoteRestore.Grid.SelectTooltip", "복원할 새 메모를 선택합니다.", "Select new notes to restore.");
            Add("NoteRestore.Column.Status", "상태", "Status");
            Add("NoteRestore.Column.Kind", "종류", "Type");
            Add("NoteRestore.Column.Game", "게임", "Game");
            Add("NoteRestore.Column.MapGameType", "맵 · 게임유형", "Map · Game Type");
            Add("NoteRestore.Column.RaidTime", "레이드 시각", "Raid Time");
            Add("NoteRestore.Column.Preview", "메모 미리보기", "Note Preview");
            Add("NoteRestore.Column.Result", "확인 결과", "Details");
            Add("NoteRestore.Count", "전체 {0}개 · 레이드 메모 {1}개 · 유저신고 메모 {2}개\r\n새로 추가될 메모 {3}개 · 기존 항목 건너뜀 {4}개", "Total: {0} · Raid notes: {1} · Report notes: {2}\r\nNew: {3} · Already saved: {4}");
            Add("NoteRestore.Selection.Description", "복원 가능한 메모 {0}개 중 {1}개가 선택되었습니다. 선택 열 머리글은 전체 선택 또는 전체 해제이며, Ctrl+A는 전체 선택입니다.", "{1} of {0} restorable notes selected. Use the selection-column header to select or clear all; Ctrl+A selects all.");
            Add("NoteRestore.Selection.ApplyCount", "선택한 새 메모 {0}개를 복원합니다.", "Restores the {0} selected new notes.");
            Add("NoteRestore.Selection.None", "복원 대상으로 선택한 새 메모가 없습니다.", "No new notes are selected for restore.");
            Add("NoteRestore.Status.New", "새로 추가", "New");
            Add("NoteRestore.Status.Existing", "기존 건너뜀", "Already Saved");
            Add("NoteRestore.Status.Conflict", "기존 내용 충돌", "Conflicting Note");
            Add("NoteRestore.Status.Unavailable", "확인 불가", "Unavailable");
            Add("NoteRestore.Status.Retry", "실패 · 재시도", "Failed · Try Again");
            Add("NoteRestore.Status.Added", "추가 완료", "Added");
            Add("NoteRestore.Status.Failed", "복원 실패", "Restore Failed");
            Add("NoteRestore.Detail.SelectionFailed", "선택한 메모를 안전하게 복원하지 못했습니다.", "The selected notes could not be restored safely.");
            Add("NoteRestore.Detail.Added", "없는 메모를 새로 추가하고 저장 결과를 확인했습니다.", "Note restored and verified.");
            Add("NoteRestore.Detail.Skipped", "같은 종류와 키의 기존 메모는 덮어쓰지 않았습니다.", "A note with this type and ID already exists and was kept.");
            Add("NoteRestore.Detail.ItemFailed", "이 항목을 안전하게 복원하지 못했습니다.", "Couldn't restore this note.");
            Add("NoteRestore.Detail.New", "없는 메모이므로 새로 추가할 수 있습니다.", "Not yet saved. Ready to restore.");
            Add("NoteRestore.Detail.Exists", "같은 종류와 키의 기존 메모가 있어 건너뜁니다.", "A note with this type and ID already exists. It will be kept.");
            Add("NoteRestore.Detail.StoreUnavailable", "현재 저장소 상태를 확인하지 못했습니다.", "Couldn't verify the saved notes.");
            Add("NoteRestore.Detail.RaceSkipped", "같은 메모가 먼저 저장되어 안전하게 건너뛰었습니다.", "This note was saved in the meantime. It was kept.");
            Add("NoteRestore.Detail.RaceConflict", "적용 전에 같은 종류와 키의 다른 메모가 생겨 덮어쓰지 않았습니다.", "A different note with this type and ID was saved in the meantime. It was kept.");
            Add("NoteRestore.EmptyPreview", "(내용 없음)", "(No content)");
            Add("NoteRestore.Header.Tooltip", "복원 가능한 새 메모를 전체 선택하거나 전체 해제합니다.", "Select or clear all restorable new notes.");
            Add("NoteRestore.Header.Name", "복원 메모 전체 선택 또는 전체 해제", "Select or Clear All Restore Notes");
            Add("NoteRestore.Header.DescriptionEmpty", "복원할 새 메모를 전체 선택하거나 전체 해제합니다.", "Select or clear all new notes to restore.");
            Add("NoteRestore.Header.Description", "복원 가능한 메모 {0}개 중 {1}개가 선택되었습니다. 클릭하면 전체 선택 또는 전체 해제합니다.", "{1} of {0} restorable notes selected. Activate to select or clear all.");

            // Manual party-IP bundles. These exact literals are compatibility keys for
            // the existing forms; user-supplied source names and IPs are never translated.
            Add("-", "-", "-");
            Add("· 로컬 표시 정보 정리 실패", "· 로컬 표시 정보 정리 실패", "· Failed to clean up local display data");
            Add(" · 로컬 표시 정보 정리 실패", " · 로컬 표시 정보 정리 실패", " · Failed to clean up local display data");
            Add(" · 임시 Party-shared {0}개 제외", " · 임시 Party-shared {0}개 제외", " · Excluded {0} temporary Party-shared entries");
            Add(" · 파티 묶음 영구 유지 표시 실패", " · 파티 묶음 영구 유지 표시 실패", " · Couldn't mark as a personal block");
            Add(" · 확인 대기", " · 확인 대기", " · Pending verification");
            Add("'{0}' 파티 묶음 {1}개 IP를 적용했습니다.", "'{0}' 파티 묶음 {1}개 IP를 적용했습니다.", "Party list '{0}' applied. IPs: {1}.");
            Add("{0} · {1}개 · {2}", "{0} · {1}개 · {2}", "{0} · {1} IPs · {2}");
            Add("{0} ({1})", "{0} ({1})", "{0} ({1})");
            Add("같은 입력에서 먼저 확인된 IP와 중복되어 적용하지 않습니다.", "같은 입력에서 먼저 확인된 IP와 중복되어 적용하지 않습니다.", "Duplicate of an earlier IP in this input. Skipped.");
            Add("개인 차단으로 유지하도록 지정되어 그대로 보존합니다.", "개인 차단으로 유지하도록 지정되어 그대로 보존합니다.", "Marked as a personal block. Kept blocked.");
            Add("공인 IPv4 형식과 현재 방화벽 상태를 확인하는 중…", "공인 IPv4 형식과 현재 방화벽 상태를 확인하는 중…", "Checking public IPv4 formats and current firewall states…");
            Add("관리자 권한 요청은 취소됐지만 파티 묶음 정보 정리에 실패했습니다.", "관리자 권한 요청은 취소됐지만 파티 묶음 정보 정리에 실패했습니다.", "Administrator access was canceled, but the pending party data couldn't be cleared.");
            Add("관리자 권한 요청이 취소되어 묶음 해제를 다시 확인해야 합니다.", "관리자 권한 요청이 취소되어 묶음 해제를 다시 확인해야 합니다.", "Administrator access was canceled. Check this party list again before removing it.");
            Add("관리자 권한 요청이 취소되었습니다.", "관리자 권한 요청이 취소되었습니다.", "The administrator permission prompt was canceled.");
            Add("구분", "구분", "Type");
            Add("기타", "기타", "Other");
            Add("다른 활성 파티 묶음 {0}개가 함께 사용하여 유지합니다.", "다른 활성 파티 묶음 {0}개가 함께 사용하여 유지합니다.", "Still used by {0} other active party lists. Kept blocked.");
            Add("마지막 참조 파티 서버 {0}개를 한 번의 관리자 권한 요청으로 해제하는 중…", "마지막 참조 파티 서버 {0}개를 한 번의 관리자 권한 요청으로 해제하는 중…", "Unblocking {0} servers used only by this party list… Approve the Windows administrator prompt to continue.");
            Add("묶음 생성 전 이미 차단됐거나 다른 활성 묶음이 함께 쓰는 IP는 절대 해제하지 않습니다. 해제 대상은 한 번의 관리자 권한 요청으로 처리합니다.", "묶음 생성 전 이미 차단됐거나 다른 활성 묶음이 함께 쓰는 IP는 절대 해제하지 않습니다. 해제 대상은 한 번의 관리자 권한 요청으로 처리합니다.", "Existing personal blocks and IPs used by other active party lists stay blocked. Windows will ask for administrator permission once to remove the eligible blocks.");
            Add("묶음 종료", "일괄 해제", "Remove Blocks");
            Add("방화벽 상태 확인이 끝난 뒤 창을 닫을 수 있습니다.", "방화벽 상태 확인이 끝난 뒤 창을 닫을 수 있습니다.", "Please wait for the firewall check to finish before closing this window.");
            Add("방화벽 차단은 확인했지만 활성 파티 묶음의 영구 유지 표시를 저장하지 못했습니다.", "방화벽 차단은 확인했지만 활성 파티 묶음의 영구 유지 표시를 저장하지 못했습니다.", "The IP is blocked, but it couldn't be marked as a personal block in the party data.");
            Add("방화벽 최종 상태는 확인했지만 파티 묶음 결과 저장을 완료하지 못했습니다.", "방화벽 최종 상태는 확인했지만 파티 묶음 결과 저장을 완료하지 못했습니다.", "Firewall status confirmed, but the party list result couldn't be saved.");
            Add("방화벽 최종 상태는 확인했지만 파티 묶음 종료 결과 저장을 완료하지 못했습니다.", "방화벽 최종 상태는 확인했지만 파티 묶음 종료 결과 저장을 완료하지 못했습니다.", "Firewall status confirmed, but the party removal result couldn't be saved.");
            Add("변경된 IP 입력을 다시 미리보기로 확인해 주세요.", "변경된 IP 입력을 다시 미리보기로 확인해 주세요.", "Preview the changed IP input again.");
            Add("보존·해제 사유", "보존·해제 사유", "Reason");
            Add("붙여넣기 입력 길이 한도를 초과했습니다.", "붙여넣기 입력 길이 한도를 초과했습니다.", "The pasted input exceeds the length limit.");
            Add("사유", "사유", "Reason");
            Add("사유: {0} · 상태: {1}", "사유: {0} · 상태: {1}", "Reason: {0} · Status: {1}");
            Add("상태 재확인 필요", "상태 재확인 필요", "Check Required");
            Add("새 파티 서버 {0}개를 한 번의 관리자 권한 요청으로 차단하는 중…", "새 파티 서버 {0}개를 한 번의 관리자 권한 요청으로 차단하는 중…", "Blocking {0} new party servers… Approve the Windows administrator prompt to continue.");
            Add("새 IP는 한 번의 관리자 권한 요청으로 함께 차단합니다.", "새 IP는 한 번의 관리자 권한 요청으로 함께 차단합니다.", "Windows will ask for administrator permission once to block the new IPs.");
            Add("새로 차단", "새로 차단", "New Block");
            Add("새로 차단 {0}개 · 이미 차단됨 {1}개 · 중복 {2}개 · 적용 제외 {3}개", "새로 차단 {0}개 · 이미 차단됨 {1}개 · 중복 {2}개 · 적용 제외 {3}개", "New: {0} · Already blocked: {1} · Duplicates: {2} · Excluded: {3}");
            Add("서버 IP", "서버 IP", "Server IP");
            Add("서버 IP 붙여넣기 · 공백, 쉼표, 세미콜론, 줄바꿈으로 구분", "서버 IP 붙여넣기 · 공백, 쉼표, 세미콜론, 줄바꿈으로 구분", "Paste server IPs · Separate with spaces, commas, semicolons, or line breaks");
            Add("선택한 묶음의 현재 방화벽 상태를 확인하는 중…", "선택한 묶음의 현재 방화벽 상태를 확인하는 중…", "Checking blocks for the selected party list…");
            Add("선택한 파티 묶음 정보", "선택한 파티 묶음 정보", "Selected Party List Details");
            Add("선택한 파티 묶음의 최신 상태를 다시 확인하는 중…", "선택한 파티 묶음의 최신 상태를 다시 확인하는 중…", "Rechecking the selected party list…");
            Add("선택한 파티 묶음이 이미 종료되었거나 존재하지 않습니다.", "선택한 파티 묶음이 이미 종료되었거나 존재하지 않습니다.", "This party list has already been removed or no longer exists.");
            Add("이 묶음 생성 전부터 차단되어 있어 그대로 유지합니다.", "이 묶음 생성 전부터 차단되어 있어 그대로 유지합니다.", "Already blocked before this list was added. Kept blocked.");
            Add("이 묶음이 마지막 참조이며 생성 전에는 차단되지 않았습니다.", "이 묶음이 마지막 참조이며 생성 전에는 차단되지 않았습니다.", "Blocked only for this list; no other party list needs it.");
            Add("이미 앱 관리 차단 규칙이 있어 묶음 참조만 추가합니다.", "이미 앱 관리 차단 규칙이 있어 묶음 참조만 추가합니다.", "Already blocked by TSG. It will also be linked to this party list.");
            Add("이미 차단됨", "이미 차단됨", "Already Blocked");
            Add("이미 해제됨", "이미 해제됨", "Already Unblocked");
            Add("임시 Party-shared 차단만 있어 개인 차단 목록 백업 파일을 저장하지 않았습니다.", "임시 Party-shared 차단만 있어 개인 차단 목록 백업 파일을 저장하지 않았습니다.", "Only temporary party blocks exist. No personal block-list backup was saved.");
            Add("입력값", "입력값", "Input");
            Add("입력이 변경되었습니다. 다시 미리보기로 확인해 주세요.", "입력이 변경되었습니다. 다시 미리보기로 확인해 주세요.", "The input changed. Preview it again.");
            Add("저장된 파티 출처 묶음을 확인하는 중…", "저장된 파티 출처 묶음을 확인하는 중…", "Loading party lists…");
            Add("적용 제외", "적용 제외", "Excluded");
            Add("적용 중", "적용 중", "Active");
            Add("적용 확인 대기", "적용 확인 대기", "Block Check Pending");
            Add("적용하면 새 앱 관리 차단 규칙을 만듭니다.", "적용하면 새 앱 관리 차단 규칙을 만듭니다.", "A new TSG block rule will be added.");
            Add("정확한 공인 IPv4가 아닙니다. 사설·예약·특수 주소도 제외합니다.", "정확한 공인 IPv4가 아닙니다. 사설·예약·특수 주소도 제외합니다.", "Not a valid public IPv4 address. Private, reserved, and special-purpose addresses are excluded.");
            Add("종료 처리", "종료 처리", "Action");
            Add("종료할 출처 묶음을 선택해 주세요.", "종료할 출처 묶음을 선택해 주세요.", "Select a party list.");
            Add("종료할 파티 출처 묶음", "해제할 파티 IP 목록", "Party List");
            Add("종료할 활성 파티 묶음이 없습니다.", "해제할 파티 차단 목록이 없습니다.", "No active party lists to remove.");
            Add("중복 제외", "중복 제외", "Duplicate");
            Add("직접 확인", "직접 확인", "Checked by Me");
            Add("차단 유지", "차단 유지", "Keep Blocked");
            Add("차단 해제", "차단 해제", "Unblock");
            Add("차단 해제 {0}개 · 상태 재확인 대기 {1}개", "차단 해제 {0}개 · 상태 재확인 대기 {1}개", "Unblocked: {0} · Need checking: {1}");
            Add("출처 구분", "출처 구분", "Source");
            Add("출처 묶음", "출처 묶음", "Party List");
            Add("출처 묶음 하나를 골라 안전하게 일괄 해제할 항목을 확인합니다.", "추가했던 파티 IP 목록을 선택하고, 차단을 해제할 IP를 확인하세요.", "Choose a party list to review which servers can be unblocked together.");
            Add("출처명", "출처명", "List Name");
            Add("취소", "취소", "Cancel");
            Add("파티 묶음 안전 해제 안내", "파티 묶음 안전 해제 안내", "Party Block Removal Policy");
            Add("파티 묶음 적용 {0}개 · 상태 재확인 대기 {1}개", "파티 묶음 적용 {0}개 · 상태 재확인 대기 {1}개", "Applied: {0} · Need checking: {1}");
            Add("파티 묶음 적용 정보를 안전하게 저장하는 중…", "파티 묶음 적용 정보를 안전하게 저장하는 중…", "Saving the party list…");
            Add("파티 묶음 정보가 손상되어 안전한 종료 작업을 시작할 수 없습니다.", "파티 묶음 정보가 손상되어 안전한 종료 작업을 시작할 수 없습니다.", "The saved party data is damaged. Blocks cannot be removed until it is recovered.");
            Add("파티 묶음 정보가 손상되어 파티 IP 추가·묶음 종료를 안전을 위해 비활성화했습니다.", "파티 묶음 정보가 손상되어 파티 IP 추가·묶음 종료를 안전을 위해 비활성화했습니다.", "The saved party data is damaged. Adding or removing party lists is unavailable until it is recovered.");
            Add("파티 묶음 정보를 안전하게 읽지 못해 종료하지 않았습니다.", "파티 묶음 정보를 안전하게 읽지 못해 종료하지 않았습니다.", "Couldn't read the saved party data. The list was kept.");
            Add("파티 묶음 정보를 저장하지 못해 방화벽 작업을 시작하지 않았습니다.", "파티 묶음 정보를 저장하지 못해 방화벽 작업을 시작하지 않았습니다.", "Couldn't save the party list. No firewall changes were made.");
            Add("파티 묶음 종료", "파티 차단 해제", "Remove Party Blocks");
            Add("파티 묶음 종료 정보를 먼저 저장하지 못해 방화벽 작업을 시작하지 않았습니다.", "파티 묶음 종료 정보를 먼저 저장하지 못해 방화벽 작업을 시작하지 않았습니다.", "Couldn't save the party removal plan. No firewall changes were made.");
            Add("파티 묶음 해제 미리보기", "파티 묶음 해제 미리보기", "Party Block Removal Preview");
            Add("파티 묶음 해제 미리보기 요약", "파티 묶음 해제 미리보기 요약", "Party Block Removal Summary");
            Add("파티 묶음을 종료했습니다. 차단 해제 {0}개 · 안전하게 유지 {1}개", "선택한 파티 목록을 처리했습니다. 차단 해제 {0}개 · 차단 유지 {1}개", "Party list removed. Unblocked: {0} · Kept blocked: {1}");
            Add("파티 서버 IP 입력", "파티 서버 IP 입력", "Party Server IPs");
            Add("파티 차단 묶음 종료", "파티 차단 해제", "Remove Party Blocks");
            Add("파티 출처 묶음별 보존·해제 대상을 미리본 뒤 안전하게 종료합니다.", "파티 IP 목록을 선택하고, 차단을 해제하거나 유지할 IP를 확인합니다.", "Choose a party list, review which blocks will be removed or kept, then confirm.");
            Add("파티 IP 미리보기 요약", "파티 IP 미리보기 요약", "Party IP Preview Summary");
            Add("파티 IP 적용 미리보기", "파티 IP 적용 미리보기", "Party IP Preview");
            Add("파티 IP 직접 입력", "파티 IP 직접 입력", "Add Party IPs");
            Add("파티 IP 차단 사유", "파티 IP 차단 사유", "Party IP Block Reason");
            Add("파티 IP 추가", "파티 IP 추가", "Add Party IPs");
            Add("파티 IP 출처명", "파티 IP 출처명", "Party List Name");
            Add("파티 IP의 출처명을 입력해 주세요.", "파티 IP의 출처명을 입력해 주세요.", "Enter a name for this party list.");
            Add("파티원 공유", "파티원 공유", "Party Member");
            Add("파티장 공유", "파티장 공유", "Party Leader");
            Add("한 번에 {0}개까지 적용할 수 있어 제외했습니다.", "한 번에 {0}개까지 적용할 수 있어 제외했습니다.", "Excluded because no more than {0} entries can be applied at once.");
            Add("한 번에 적용", "한 번에 적용", "Block IPs");
            Add("해제 {0}개 · 안전하게 유지 {1}개 · 이미 없음 {2}개 · 확인 대기 {3}개", "해제 {0}개 · 안전하게 유지 {1}개 · 이미 없음 {2}개 · 확인 대기 {3}개", "To unblock: {0} · Keep blocked: {1} · Already unblocked: {2} · Need checking: {3}");
            Add("해제 미리보기를 만들지 못했습니다. 묶음 정보를 다시 확인해 주세요.", "해제 미리보기를 만들지 못했습니다. 묶음 정보를 다시 확인해 주세요.", "Couldn't prepare the removal preview. Check the party list and try again.");
            Add("해제 확인 대기", "해제 확인 대기", "Unblock Check Pending");
            Add("현재 방화벽 상태를 확인하지 못해 적용에서 제외합니다.", "현재 방화벽 상태를 확인하지 못해 적용에서 제외합니다.", "Couldn't check the firewall status. Skipped.");
            Add("현재 상태를 확인하지 못해 안전을 위해 자동 해제하지 않습니다.", "현재 상태를 확인하지 못해 안전을 위해 자동 해제하지 않습니다.", "Status unknown. The block will be kept until it can be checked.");
            Add("현재 앱 관리 차단 규칙이 없어 묶음 정보만 정리합니다.", "현재 앱 관리 차단 규칙이 없어 묶음 정보만 정리합니다.", "Already unblocked. Only the saved party link will be removed.");
            Add("확인 결과", "확인 결과", "Details");
            Add("확인 대기", "확인 대기", "Check Pending");
            Add("활성 또는 처리 대기 파티 묶음 {0}개를 확인했습니다.", "활성 또는 처리 대기 파티 묶음 {0}개를 확인했습니다.", "Active or pending party lists: {0}.");
            Add("IP 미리보기", "IP 미리보기", "Preview IPs");
            Add("IP를 입력한 뒤 미리보기로 새 차단·기존 차단·제외 항목을 확인하세요.", "IP를 입력한 뒤 미리보기로 새 차단·기존 차단·제외 항목을 확인하세요.", "Enter IPs, then preview new blocks, existing blocks, and excluded entries.");
            Add("P2P 없이 전달받은 공인 IPv4를 출처 묶음으로 미리본 뒤 이 PC에 적용합니다.", "P2P 없이 전달받은 공인 IPv4를 출처 묶음으로 미리본 뒤 이 PC에 적용합니다.", "Paste the public IPv4 addresses shared by your party, preview them, and block them on this PC.");
            Add("P2P·자동 동기화 없이 받은 공인 IPv4를 이 PC에만 적용합니다.", "P2P·자동 동기화 없이 받은 공인 IPv4를 이 PC에만 적용합니다.", "Shared IPs are blocked on this PC only. Party lists are not synced automatically or sent to other players.");
            Add("Party-shared", "Party-shared", "Party-shared");
            Add("Party-shared · {0}", "Party-shared · {0}", "Party-shared · {0}");
            Add("Party-shared · {0}개 묶음", "Party-shared · {0}개 묶음", "Party-shared · {0} lists");
            Add("Party-shared 출처: {0}\r\n방화벽 규칙: {1}", "Party-shared 출처: {0}\r\n방화벽 규칙: {1}", "Party-shared source: {0}\r\nFirewall rule: {1}");
            // English review: dialogs, static documents, and compact presentation.
            Add("PartyInput.SharedBy", "사유", "Shared By");
            Add("BlockRestore.Select", "적용", "Apply");
            Add("License.CloseButton", "확인", "Close");
            Add("PatchNotes.CloseButton", "확인", "Close");
            Add("Diagnostic.NewBlock", "새 앱 관리 규칙으로 차단합니다.", "A new TSG block rule will be added.");
            Add("Diagnostic.AlreadyBlocked", "이미 앱 관리 규칙으로 차단되어 있습니다.", "Already blocked by TSG.");
            Add("Diagnostic.FirewallUnknown", "현재 방화벽 상태를 확인하지 못했습니다.", "Couldn't check the current firewall status.");
            Add("Diagnostic.FinalFirewallUnknown", "방화벽 상태를 최종 확인하지 못했습니다.", "Couldn't confirm the final firewall status.");
            Add("Diagnostic.InvalidItem", "항목 형식이 올바르지 않습니다.", "Invalid entry format.");
            Add("Diagnostic.UnsupportedFields", "지원하지 않는 항목 필드가 포함되어 있습니다.", "This entry contains unsupported fields.");
            Add("Diagnostic.MissingIp", "서버 IP가 없거나 문자열이 아닙니다.", "The server IP is missing or is not text.");
            Add("Diagnostic.InvalidPublicIp", "정확한 공인 IPv4 주소가 아닙니다.", "Not a valid public IPv4 address.");
            Add("Diagnostic.DuplicateIp", "같은 파일 안에 중복된 서버 IP입니다.", "Duplicate IP in this backup file.");
            Add("Diagnostic.InvalidFieldType", "{0} 값이 문자열 또는 null이 아닙니다.", "{0} must be text or null.");
            Add("Diagnostic.InvalidFieldText", "{0} 값의 길이 또는 문자가 올바르지 않습니다.", "{0} contains invalid characters or exceeds the length limit.");
            Add("Diagnostic.InvalidFieldTime", "{0} 값이 올바른 UTC 시각이 아닙니다.", "{0} is not a valid UTC timestamp.");
            Add("Diagnostic.BackupTooLarge", "백업 파일 크기 한도를 초과했습니다.", "The backup file exceeds the size limit.");
            Add("Diagnostic.BackupInvalid", "비어 있거나 올바르지 않은 백업 파일입니다.", "The backup file is empty or invalid.");
            Add("Diagnostic.BackupEncoding", "백업 파일이 올바른 UTF-8 형식이 아닙니다.", "The backup file is not valid UTF-8.");
            Add("Diagnostic.BackupDuplicateField", "백업 JSON에 중복된 필드가 포함되어 있습니다.", "The backup contains duplicate JSON fields.");
            Add("Diagnostic.BackupJson", "백업 JSON 형식을 읽을 수 없습니다.", "Couldn't read the backup's JSON data.");
            Add("Diagnostic.BackupRoot", "백업 JSON의 최상위 형식이 올바르지 않습니다.", "The backup's top-level JSON structure is invalid.");
            Add("Diagnostic.BackupRootFields", "지원하지 않는 최상위 필드가 포함되어 있습니다.", "The backup contains unsupported top-level fields.");
            Add("Diagnostic.BackupVersion", "지원하지 않는 차단 목록 백업 형식 또는 버전입니다.", "Unsupported block-list backup format or version.");
            Add("Diagnostic.BackupItems", "백업 항목 목록 형식이 올바르지 않습니다.", "The backup's entry list is invalid.");
            Add("Diagnostic.BackupItemLimit", "백업 항목 수가 한도({0}개)를 초과했습니다.", "The backup contains more than {0} entries.");
            Add("Diagnostic.BackupServerLimit", "차단 서버가 {0}개여서 백업 한도({1}개)를 초과했습니다.", "There are {0} blocked servers. The backup limit is {1}.");
            Add("Diagnostic.AdminCanceled", "관리자 권한 요청이 취소되었습니다.", "The administrator permission prompt was canceled.");
            Add("Diagnostic.AdminStart", "관리자 권한 작업을 시작하지 못했습니다.", "Couldn't start the operation with administrator permission.");
            Add("Diagnostic.InvalidIp", "유효하지 않은 IPv4 주소입니다.", "Invalid IPv4 address.");
            Add("Diagnostic.InvalidIpShort", "유효하지 않은 IPv4 주소", "Invalid IPv4 address.");
            Add("Diagnostic.RuleMissing", "앱 관리 차단 규칙이 확인되지 않았습니다.", "Couldn't find the TSG block rule.");
            Add("Diagnostic.RuleCollision", "같은 이름의 다른 방화벽 규칙이 있어 삭제하지 않았습니다.", "A different firewall rule has the same name. It was kept.");
            Add("Diagnostic.RuleRemains", "관리 규칙이 남아 있어 해제를 완료하지 못했습니다.", "A TSG rule is still present. The server could not be fully unblocked.");
            Add("Diagnostic.WriteBusy", "다른 창에서 메모를 저장하고 있습니다. 잠시 후 다시 시도해 주세요.", "A note is being saved in another window. Try again in a moment.");
            Add("Diagnostic.RaidNoteCorrupt", "기존 레이드 메모와 복구본을 읽을 수 없어 저장하지 않았습니다. 원본 파일을 확인해 주세요.", "The raid note and its recovery copy couldn't be read. Nothing was saved. Check the original files.");
            Add("Diagnostic.ReportNoteCorrupt", "기존 유저신고 메모와 복구본을 읽을 수 없어 저장하지 않았습니다. 원본 파일을 확인해 주세요.", "The report note and its recovery copy couldn't be read. Nothing was saved. Check the original files.");
            Add("Diagnostic.ReportNoteTooLarge", "유저신고 메모 데이터가 허용 크기를 초과했습니다.", "This report note exceeds the size limit.");
            Add("Diagnostic.ReportBackupIncomplete", "일부 유저신고 메모를 읽지 못해 불완전한 백업을 만들지 않았습니다.", "Some report notes couldn't be read. No backup was created because it would be incomplete.");
            Add("Diagnostic.Unknown", "오류 내용을 확인하지 못했습니다.", "Couldn't verify the operation. Try again.");
            Add("Main.Privacy.CompactNotice", "로그와 계정 정보는 이 PC에서만 처리합니다.", "Logs, account data, SIDs and paths stay on this PC.\r\nAdmin access: blocking and unblocking only.\r\nIP locations: local DB-IP Lite, no lookup API.\r\nMonthly DB updates during scans: ~60–70 MB.\r\nUpdate checks connect to GitHub Releases.\r\nDB-IP.com · CC BY 4.0");
            Add("PatchNotes.Empty", "이 버전에는 별도의 변경 사항 내용이 제공되지 않았습니다.", "No release notes were provided for this version.");
            Add("PatchNotes.Truncated", "[표시할 수 있는 최대 길이를 넘어 나머지 내용은 생략했습니다.]", "[The remaining text exceeds the display limit and has been omitted.]");
            Add("UpdateDialog.Prompt", "Tarkov Server Guard v{0} 업데이트가 있습니다.\r\n지금 업데이트하시겠습니까?", "Tarkov Server Guard v{0} is available.\r\nUpdate now?");
            Add("UpdateDialog.Progress", "다운로드 {0}%", "Downloading… {0}%");
            Add("License.Summary", "개인적·비상업적 사용은 무료입니다.\r\n소스코드는 안전성과 투명성 확인을 위해 공개합니다.\r\n제작자의 허가 없는 수정본 배포, 재배포, 판매 및 상업적 이용을 금지합니다.\r\n공식 배포처는 Spirit-Schema GitHub Releases입니다.\r\n비공식 배포본은 안전성과 정상 작동을 보증하거나 지원하지 않습니다.", "Free for personal, noncommercial use.\r\nThe source code is available for security review and transparency.\r\nRedistribution, distribution of modified versions, sale, and commercial use require the author's permission.\r\nOfficial downloads: Spirit-Schema on GitHub Releases.\r\nUnofficial builds are unsupported; their safety and operation are not guaranteed.");
            Add("PatchNotes.Heading", "v{0} 업데이트가 완료되었습니다.", "Updated to v{0}");
            Add("BlockRestore.Policy", "선택한 새 IP만 이 PC의 Windows 방화벽에 한 번의 관리자 권한 요청으로 추가합니다.\r\n이미 저장된 지역·메모·차단시각은 덮어쓰지 않고 비어 있는 정보만 복원합니다.", "Selected new IPs are blocked on this PC with one administrator prompt.\r\nOnly missing region, note, and block-time details are restored. Existing details are kept.");
            Add("BlockRestore.None", "없음", "None");
            Add("BlockRestore.DataCenter", "데이터센터", "Data Center");
            Add("BlockRestore.Region", "지역", "Region");
            Add("UpdateDialog.Title", "Tarkov Server Guard 업데이트", "Update Tarkov Server Guard");
            Add("UpdateDialog.Heading", "새 버전이 있습니다", "Update Available");
            Add("UpdateDialog.Update", "업데이트", "Update");
            Add("UpdateDialog.Later", "나중에", "Later");
            Add("UpdateDialog.Downloading", "업데이트를 다운로드하고 있습니다.\r\n완료되면 자동으로 다시 시작합니다.", "Downloading the update.\r\nTSG will restart when it is ready.");
            Add("UpdateDialog.Preparing", "다운로드 준비 중...", "Preparing download…");
            Add("UpdateDialog.DownloadError", "업데이트하지 못했습니다. 현재 버전은 그대로 유지됩니다.\r\n잠시 후 다시 시도해 주세요.", "Couldn't download the update. You're still on the current version.\r\nTry again later.");
            Add("UpdateDialog.ApplyError", "업데이트를 적용하지 못했습니다. 현재 버전은 그대로 유지됩니다.\r\n잠시 후 다시 시도해 주세요.", "Couldn't install the update. You're still on the current version.\r\nTry again later.");
            Add("UpdateDialog.Retry", "다시 시도", "Try Again");
            Add("PatchNotes.Title", "Tarkov Server Guard 업데이트 완료", "Tarkov Server Guard Updated");
            Add("PatchNotes.A11y", "업데이트 완료 안내", "Update Complete");
            Add("PatchNotes.VersionA11y", "업데이트 완료 버전", "Installed Version");
            Add("PatchNotes.Intro", "이번 업데이트에 포함된 변경 사항입니다. 이 안내는 해당 버전 업데이트 후 한 번만 표시됩니다.", "Here's what's new. This notice appears once after each update.");
            Add("PatchNotes.IntroA11y", "일회성 업데이트 안내", "One-Time Update Notice");
            Add("PatchNotes.Changes", "업데이트 변경 사항", "What's New");
            Add("PatchNotes.ChangesA11y", "앱에 포함된 읽기 전용 업데이트 변경 사항", "Read-only release notes included with the app.");
            Add("PatchNotes.ConfirmA11y", "업데이트 완료 안내 확인", "Dismiss Update Notice");
            Add("License.Title", "라이선스 및 저작권", "License & Copyright");
            Add("License.Document", "라이선스 전문", "Full License");
            Add("License.ThirdParty", "서드파티 고지", "Third-Party Notices");
            Add("License.DocumentA11y", "라이선스 문서 내용", "License Document");
            Add("License.DocumentHelp", "선택한 라이선스 또는 서드파티 고지의 전체 내용", "Full text of the selected license or third-party notices.");
            Add("License.ShowHelp", "프로그램 라이선스 전문을 표시합니다.", "Read the full application license.");
            Add("License.ThirdPartyHelp", "제3자 구성요소의 저작권과 라이선스 고지를 표시합니다.", "Read copyright and license notices for third-party components.");
            Add("License.CloseHelp", "라이선스 및 저작권 창을 닫습니다.", "Close License & Copyright.");
            Add("License.BilingualTitle", "라이선스 전문 · 한국어 / English", "Full License · Korean / English");
            Add("License.LoadFailed", "문서를 불러오지 못했습니다. 공식 배포본의 파일 구성을 확인해 주세요.", "Couldn't load the document. Check that you have all files from the official release.");
            Add("BlockRestore.Title", "차단 목록 복원 미리보기", "Restore Block List");
            Add("BlockRestore.Count", "새로 차단 {0}개 · 이미 차단됨 {1}개 · 적용 제외 {2}개", "New: {0} · Already blocked: {1} · Excluded: {2}");
            Add("BlockRestore.PolicyA11y", "개인 차단 목록 복원 안내", "Personal Block List Restore Policy");
            Add("BlockRestore.Apply", "선택 항목 복원", "Restore Selected");
            Add("BlockRestore.Metadata", "백업 정보", "Saved Details");
            Add("BlockRestore.BlockTime", "차단시각", "Blocked At");
            Add("BlockRestore.Results", "차단 목록 복원 결과", "Block List Restore Results");
            Add("BlockRestore.Failures", "최종 앱 관리 차단 규칙을 확인하지 못한 항목이 {0}개 있습니다.", "Couldn't confirm the final block status for {0} IPs.");
            Add("BlockRestore.FailureReason", "실패 사유", "Reason");
        }
    }
}
